version: '3.3'

services:

  # polish version of BARF-o-bot core app
  instance:
    image: rasa/rasa:latest-full
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./config:/app/config
      - ./models:/app/models
      - ./logs:/app/logs
    ports:
      - 5101:5005
    env_file:
      - .env
    command:
      - run
      - --debug
      - --model
      - "models/model.tar.gz"
      - --log-file
      - "logs/logs.txt"
      - --endpoints
      - "config/endpoints.yml"
      - --cors
      - "*"
      - --credentials
      - "config/credentials.yml"

  # custom action server for BARF-o-bot
  actions:
    image: barfobot_actions:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./actions:/app/actions
      - ./config:/app/config
      - ./utils:/app/utils
    ports:
      - 5102:5055
    env_file:
      - .env
    command:
      - start
      - --actions
      - actions
    depends_on:
      - instance

  # duckling extractor service
  duckling:
    image: rasa/duckling:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 9000:9000
    command:
      - duckling-example-exe
      - --no-access-log
      - --no-error-log
      - -p
      - "9000"
    depends_on:
      - instance

  # postgres service to store events
  postgres:
    image: postgres:latest
    volumes:
      - ./db_storage:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - instance
