action_endpoint:
  url: "http://actions:5055/webhook"

tracker_store:
  type: sql
  dialect: "postgresql"
  url: postgres
  db: ${POSTGRES_DB}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
