action_endpoint:
  url: "http://actions:5055/webhook"

tracker_store:
  type: sql
  dialect: "postgresql"
  url: postgres
  db: ${DATABASE_NAME}
  username: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
