action_endpoint:
  url: "http://actions:5055/webhook"

tracker_store:
  type: sql
  dialect: "postgresql"
  url: postgres
  db: barfobot_store
  username: barfobot
  password: ${BARFOBOT_STORE_PASSWORD}